New Option: numthreads
mslehre/pst19-spielplatz pull request #20
Opened 2021-04-09 15:52 UTC by PetulaDiemke

Add option numthreads to do.cc

2021-04-09 18:12 UTC, MarioStanke requested changes
1. Sie haben viele Zeilen verändert, die nicht zu dem commit gehören. Wenn Sie in dem Code anderer weitere Änderungen machen wollen (hier: Einrückung), dann sollten Sie das in zwei Commits aufteilen. Dann kann man sie einzeln berücksichtigen (cherry-pick) oder rückgängig machen.
2. Sie sollten den Coding Style beibehalten. Es muss einheitlich sein, weil es sonst ein Tauziehen (Hin- und Her) von Änderungen im Format gibt. Hier waren es 4 Leerzeichen pro Einrückungsstufe.

2021-04-09 18:41 UTC, PetulaDiemke commented
Entschuldigung, das mache ich wieder rückgängig und nächstes Mal natürlich in mehreren commits, das hatte ich nicht bedacht. Ich war nur verwirrt, weil am Anfang des Codes vor allem mit Leerzeichen, an einigen Stellen aber auch nur mit tabs (z. B. Zeile 36 des ursprünglichen Codes) und teilweise auch mit einer Mischung aus beidem (z. B. Zeile 46) eingerückt wurde. Deswegen hab ich mich dann für tabs entschieden, aber ich hätte natürlich vorher nachfragen sollen. 
Soll ich die anderen Zeilen auch mit Schritten aus jeweils 4 Leerzeichen einrücken oder soll ich den ursprünglichen Code wiederherstellen und nur meine Zeilen hinzufügen?

2021-04-09 18:54 UTC, MarioStanke commented
Sie brauchen sich nicht zu entschuldigen und können auch eine inkonsistente Einrückung verbessern. Ich habe nur recht ausführlich reagiert, weil das aus Erfahrung oft ein Problem ist. 
Die Mischung aus Tab und Spaces ist ein regulärer Codierstil, die letzten White Spaces sind dann Spaces. Das ist letztlich Geschmacksache.
Dass in Zeile 36 mit Tab eingerückt ist, ist ein Fehler. Den sollte einer korrigieren. Sie können das gerne als zweiten Commit mit in dem Pull-Request packen.

2021-04-11 15:28 UTC, MarioStanke requested changes

2021-04-11 15:28 UTC, MarioStanke commented on exercise1/do.cc
> +		numthreads = strtoul(optarg,nullptr,10);
```suggestion
		numthreads = strtoul(optarg, nullptr, 10);
```

2021-04-11 15:28 UTC, MarioStanke commented on exercise1/do.cc
> +		numthreads = strtoul(optarg,nullptr,10);
Use same style as elsewhere in the code.

2021-04-11 15:29 UTC, merged

2021-04-11 15:31 UTC, MarioStanke commented
All good. I fixed a small issue myself.